#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff --name-only origin/main | grep -q '^apps/wow-docs/'; then
  
  pnpm wow-docs:codegen && pnpm svg-optimize && pnpm styled-system:format && pnpm build
  
else
  pnpm codegen:build
fi
