#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed_files=$(git diff --name-only origin/main)

wow_docs_changes=$(echo "$changed_files" | grep '^apps/wow-docs/' || true)

other_changes=$(echo "$changed_files" | grep -v '^apps/wow-docs/' || true)

if [ -n "$wow_docs_changes" ] && [ -z "$other_changes" ]; then
  pnpm wow-docs:codegen && pnpm svg-optimize && pnpm styled-system:format && pnpm build

elif [ -n "$wow_docs_changes" ] && [ -n "$other_changes" ]; then
  pnpm wow-docs:codegen && pnpm svg-optimize && pnpm styled-system:format && pnpm build && pnpm codegen:build

elif [ -z "$wow_docs_changes" ] && [ -n "$other_changes" ]; then
  pnpm codegen:build

else
  
fi