name: "a11y-test"

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/wow-ui/src/**

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Dependency
        run: pnpm install --no-frozen-lockfile
        working-directory: packages/wow-ui

      - name: Serve Storybook and run tests
        run: pnpm storybook && pnpm test-storybook
        working-directory: packages/wow-ui
