name: "release"

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup-node-pnpm: 
    uses: GDSC-Hongik/wow-design-system/.github/workflows/setup-node-pnpm.yml@feature/project-setting
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: setup-node-pnpm
    steps:
      - name: Install Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
        
      - name: Install Dependency
        run: pnpm install --no-frozen-lockfile
        working-directory: packages/wow-ui

      - name: Build packages
        run: pnpm build

      - name: Create .npmrc file
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=gdsc.hongik@gmail.com
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
